### ISSUE TITLE
proto file

### ISSUE THREAD

**Issue by daofeng2015** [Akebi-Group/Akebi-PacketSniffer#2]
Where can I get the proto file? https://github.com/Grasscutters/Grasscutter/tree/development/proto Here?

**Comment by CPP-Callow** [comment]
Yes

**Comment by daofeng2015** [comment]
> Yes, but sniffer still don't support this format. So you should put all CMD ID's to the separated file.

I have filled in the directory path and it shows that the connection was successful, but there is no log

**Comment by Winter-is-comingXK** [comment]
> 

真是焜服了，发又毳不发全

**Comment by Winter-is-comingXK** [comment]
> > > Yes
> > 
> > 
> > > > Yes, but sniffer still don't support this format. So you should put all CMD ID's to the separated file.
> > > 
> > > 
> > > I have filled in the directory path and it shows that the connection was successful, but there is no log
> > 
> > 
> > Yeah, I updated answer. You should use `SeparateFile` and specify file with ids what was described above.
> 
> You should put those modified files in the repository as well
康康这个
https://github.com/Grasscutters/Grasscutter/blob/712d17631f95ab14e7a332645fe0f7cf1e4fafbd/src/main/java/emu/grasscutter/net/packet/PacketOpcodes.java

**Comment by Winter-is-comingXK** [comment]
https://github.com/Winter-is-comingXK/Akebi-PacketSniffer/tree/mod
