### ISSUE TITLE
PacketHead.proto File not found

### ISSUE THREAD

**Issue by killercc** [Akebi-Group/Akebi-PacketSniffer#4]
[Error] [ProtoParser.cpp:207] Failed to parse message with name PacketHead.
Error while parsing PacketHead.proto file, line -1, column 0, error: File not found.

**Comment by Wansn-w** [comment]
you need to prepare your own Protos, this project already supports the use of [Grasscutter-Protos](https://github.com/Grasscutters/Grasscutter-Protos) in https://github.com/Akebi-Group/Akebi-PacketSniffer/commit/84ac17c00b837070775094ab8e367d537ee06678
